version: "3.3"

services:
  nextjs:
    container_name: component-store-container
    ports:
      - 3000:3000
    build:
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/.next
    links:
      - mongo
    env_file:
      - .env
  mongo:
    container_name: localhost
    image: localhost
    ports:
      - '27017:27017'